version: "2"
checks:
  return-statements:
    config:
      threshold: 5
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true

checks:
  return-statements:
    config:
      threshold: 6

exclude_patterns:
  - "!**/**.go"
  - "**/*_test.go"
  - "resource/resource_list.go"
